### ISSUE TITLE
ROS2 foxy support

### ISSUE THREAD

**Issue by ShaiGuliMorad** [ros-sports/rqt_image_overlay#43]
are there any limitation that prevent porting to foxy?
if it's possible could you direct me to what i should look into in the code?

**Comment by ijnek** [comment]
Hi @ShaiGuliMorad thank you for showing interesting in using this package.
Porting this to foxy is difficult because of the GenericSubscribe feature of rclcpp that this package relies on heavily, which was [only added in Galactic](https://github.com/ros2/rclcpp/pull/1452).

I found a [similar thread from another project](https://github.com/ros2/domain_bridge/issues/59) which also mentions that it would require significant work to get it working.

**Comment by ijnek** [comment]
I'm going to close this one off as there doesn't seem any actionables here.
