### ISSUE TITLE
Links to implementations of overlay layers

### ISSUE THREAD

**Issue by BrettRD** [ros-sports/rqt_image_overlay#52]
This package is great and is getting used, but it's hard to find implementations of common layers
It would be great if the project (readme or docs) had a list where people can PR links to their layers

https://github.com/ros-sports/vision_msgs_layers
https://github.com/ros-sports/soccer_vision_2d_layers
https://github.com/Kettenhoax/apriltag_overlay_plugins

**Comment by ijnek** [comment]
Thanks @BrettRD! As per your suggestion, I've raised a [PR against rqt_image_overlay-docs](https://github.com/ros-sports/rqt_image_overlay-docs/pull/6). Would you be able to review?

**Comment by BrettRD** [comment]
It would be nice if this repo's readme also linked to its dependencies and available layers
It would save people a few seconds of fighting rosdep if they've come via index.ros.org, or from a workspace sitting on a robot

**Comment by ijnek** [comment]
I think listing dependencies in the README is beyond the scope, and that's something ROS Index is really good at automatically doing.

In regards to available layers, none of the layers listed have been released into the ROS ecosystem (if they do get released, you'l see them show up under "dependant packages" on ROS index so I think it shouldn't be an issue). 

By the way, what did you mean when you say "fighiting rosdep"? Perhaps I'm not quite understanding your point.

**Comment by BrettRD** [comment]
> By the way, what did you mean when you say "fighiting rosdep"? Perhaps I'm not quite understanding your point.
It's a throwaway comment, it's hard to get rosdep to simply list missing packages

When I have a problem on a robot, I typically check the readmes before I load a browser, especially if the robot is in the middle of a paddock
The best presented packages have setup instructions in the readme, even if the instructions are trivial, just so that a basic manual moves with the code.

A lot of great packages are released to a git server and never make it to the index, your package suffers for their lack of visibility

I appreciate the effort that's gone into the docs, but that doesn't make the readme redundant

**Comment by ijnek** [comment]
> When I have a problem on a robot, I typically check the readmes before I load a browser, especially if the robot is in the middle of a paddock

Is this due to lack of internet access? Providing help for a package without internet access isn't something I've thought of. You may know this, but ReadTheDocs gives you options for generating a very nice pdf, or downloading the html files as an option in the bottom-left pane, which you could utilize if you're going to be away from internet:

![image](https://user-images.githubusercontent.com/18237662/198035330-4f727ac4-c6ed-41aa-9bc2-43db09ce22c5.png)

I'd prefer to keep all documentation in one place, rather than having it split up into the README and somewhere else. In my opinion RTD/Sphinx is by far the easiest user interface for instructions / tutorials (not API docs) and hence why I've stuck with RTD for everything.

> A lot of great packages are released to a git server and never make it to the index, your package suffers for their lack of visibility

In regards to this point, yes this is unfortunate that many don't get released. Nonetheless, the non-released packages have been listed in the docs now so this should be good!
